image: node:7.9.0

pages:
  stage: deploy
  cache:
    paths:
      - node_modules
  script:
    - yarn
    - yarn build
    # - mkdir .public
    - rm -rf public/*
    - cp -r build/* public
    # - rm -rf public
    # - mkdir public
    # - mv .public/* public
    - ls public
  artifacts:
    paths:
    - public
  only:
  - master