export const columns = [
  {name: 'number', description: 'N'},
  {name: 'name', description: 'Name'},
  {name: 'plateAppearances', description: 'PA'},
  {name: 'atBats', description: 'AB'},
  {name: 'hits', description: 'HITS'},
  {name: 'singles', description: '1B'},
  {name: 'doubles', description: '2B'},
  {name: 'triples', description: '3B'},
  {name: 'home_runs', description: 'HR'},
  {name: 'runsOverErrors', description: 'ROE'},
  {name: 'hitByPitch', description: 'HBP'},
  {name: 'sac_flies', description: 'SF'},
  {name: 'sac_hits', description: 'SAC'},
  {name: 'walks', description: 'BB'},
  // {name: 'walksAvg', description: 'BB %'},
  {name: 'strikeOuts', description: 'SO'},
  // {name: 'strikeOutsAvg', description: 'SO %'},
  {name: 'rbi', description: 'RBI'},
  {name: 'runs', description: 'RUNS'},
  {name: 'avg', description: 'AVG'},
  {name: 'obp', description: 'OBP'},
  {name: 'slg', description: 'SLG'},
  {name: 'stolenBases', description: 'SB'},
  // {name: 'stolenBasesAttempts', description: 'SB attempts'},
  // {name: 'stolenBasesAvg', description: 'SB %'},
]